bot:
  token: 'MTMwNjEyNDI3ODM0NDk3NDM2Nw.GLx1xu.EV_hv97E6DUTPRO3S7E5RshnSSdpdUqM7iuPNM'
  guild_ids:
    # Enabled guilds
    # First guild id is default
    - 1215463728439500801
    - 1335854779217350679
  locale_ids:
    EN: 10001
    PT: 10001
    ZH: 10001
  level_post_channel_id: 1335854837421838386
  booster_role_id: 1268753494832054335
  stage_moderator_role_id: 1279034104561668177
  member_role_id: 1279815330566508627
  rich_presence:
    enabled: true
    activities:
      - type: competing
        name: "SMM:WE"
        status: online
      - type: playing
        name: "Creating awesome levels in SMM:WE"
        status: online
      - type: watching
        name: "How nice the Staff is UwU"
        status: online
      - type: competing
        name: "Engine Bot vs Coursebot"
        status: dnd


enginetribe_api:
  host: "http://104.243.47.202:35783"
  api_key: "enginetribe"
  tokens:
    EN: "000001"
    ES: "000002"
    PT: "000003"
    ZH: "000004"


webhook: # To upload level files
  host: "0.0.0.0"
  port: 5586